version: '3'

services:
  web:
#    image: f1rstov/rest_example_web:4
    build: ./
    command: python manage.py runserver 0.0.0.0:8090
    ports:
      - '8090:8090'
    depends_on:
      - db
  migrate:
    #    image: f1rstov/rest_example_web:4
    build: ./
    command: python manage.py migrate
    ports:
      - '8090:8090'
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres